blank_issues_enabled: true
contact_links:
  - name: View & Search design systems 🎨
    url: https://www.designsystemcookbooks.com/
    about: Check Design System Cookbooks' website, and search from a list of 100+ design systems.